import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import { SidebarInset, SidebarProvider } from '../components/base/sidebar'
import { AppSidebar } from '../components/layout/appSidebar'
import { AppThemeProvider } from '../shared/react/providers/appThemeProvider'
import './globals.css'



/* const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin', 'latin-ext', 'devanagari'],
  weight: ['100', '200', '300', '400', '500', '600']
}) */

const outfit = Outfit({
  variable: '--font-outfit',
  subsets: ['latin', 'latin-ext'],
  weight: ['100', '200', '300', '400', '500', '600', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${outfit.variable} antialiased`}
      >
        <AppThemeProvider>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              {children}
            </SidebarInset>
          </SidebarProvider>
        </AppThemeProvider>
      </body>
    </html>
  )
}
